openapi: 3.0.3
info:
  title: Smart aviation test - OpenAPI 3.0
  description: |-
    Smart aviation test
  version: 1.0.0
servers:
  - url: '{protocol}://localhost:8080/api/'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
    description: Localhost
  - url: '{protocol}://smart-aviation.com/api/'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
    description: Dev
tags:
  - name: auth
    description: auth
components:
  schemas:
    GenericResponseDto:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
    GenericErrorResponseDto:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        errors:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ErrorResponseDto'
    ErrorResponseDto:
      type: object
      properties:
        description:
          type: string
        message:
          type: string
paths:
  ############ AUTH #############
  /flight-info:
    $ref: 'flight/flight-info.yml#/paths/~1flight-info'
  /flight-info/iata:
    $ref: 'flight/flight-info.yml#/paths/~1flight-info~1iata'